# Generated by Django 4.2.2 on 2023-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0002_event_team_remove_event_ind_is_individual_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_h2h',
            name='score_type',
            field=models.CharField(choices=[('B', 'Binary'), ('I', 'Integer'), ('1', 'Decimal_1'), ('2', 'Decimal_2'), ('3', 'Decimal_3'), ('4', 'Decimal_4'), ('F', 'Decimal_Float')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='score_type',
            field=models.CharField(choices=[('B', 'Binary'), ('I', 'Integer'), ('1', 'Decimal_1'), ('2', 'Decimal_2'), ('3', 'Decimal_3'), ('4', 'Decimal_4'), ('F', 'Decimal_Float')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='event_team',
            name='score_type',
            field=models.CharField(choices=[('B', 'Binary'), ('I', 'Integer'), ('1', 'Decimal_1'), ('2', 'Decimal_2'), ('3', 'Decimal_3'), ('4', 'Decimal_4'), ('F', 'Decimal_Float')], default='I', max_length=1),
        ),
    ]
