# Generated by Django 4.2.2 on 2023-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0003_event_h2h_score_type_event_ind_score_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brolympics',
            name='projected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brolympics',
            name='projected_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_h2h',
            name='projected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_h2h',
            name='projected_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='projected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='projected_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_team',
            name='projected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_team',
            name='projected_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
