# Generated by Django 4.2.2 on 2023-07-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0004_brolympics_projected_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brolympics',
            name='hashid',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='league',
            name='hashid',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='hashid',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
