# Generated by Django 4.2.2 on 2023-07-22 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brolympics', '0005_brolympics_hashid_league_hashid_team_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='brolympics',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='brolympics/'),
        ),
        migrations.AddField(
            model_name='brolympics',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='brolympics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/'),
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
