# Generated by Django 4.2.2 on 2023-07-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0009_alter_event_h2h_n_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_picture',
        ),
    ]
