# Generated by Django 4.2.2 on 2023-07-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0013_alter_team_player_1_alter_team_player_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='brolympics',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='brolympics.brolympics'),
            preserve_default=False,
        ),
    ]
