# Generated by Django 4.2.2 on 2023-07-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0014_alter_team_brolympics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_h2h',
            name='max_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event_h2h',
            name='min_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event_ind',
            name='max_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event_ind',
            name='min_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event_team',
            name='max_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event_team',
            name='min_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
