# Generated by Django 4.2.2 on 2023-07-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0016_event_h2h_is_active_event_ind_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_h2h',
            old_name='is_concluded',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='event_ind',
            old_name='is_concluded',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='event_team',
            old_name='is_concluded',
            new_name='is_complete',
        ),
    ]
