# Generated by Django 4.2.2 on 2023-07-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0018_competition_team_display_avg_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='brolympics.event_ind'),
        ),
        migrations.AlterField(
            model_name='competition_team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='brolympics.event_team'),
        ),
    ]
