# Generated by Django 4.2.2 on 2023-07-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0019_remove_team_score_alter_competition_ind_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallbrolympicsranking',
            name='event_podiums',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallbrolympicsranking',
            name='event_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
