# Generated by Django 4.2.2 on 2024-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0020_overallbrolympicsranking_event_podiums_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='img',
            new_name='img_url',
        ),
        migrations.AlterField(
            model_name='brolympics',
            name='img',
            field=models.ImageField(blank=True, default='/default_bro/image_8.webp', null=True, upload_to='brolympics/'),
        ),
    ]
