# Generated by Django 4.2.2 on 2024-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0021_rename_img_league_img_url_alter_brolympics_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='img_url',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='brolympics',
            name='img',
            field=models.ImageField(blank=True, default='/default_bro/image_5.webp', null=True, upload_to='brolympics/'),
        ),
    ]
