# Generated by Django 4.2.2 on 2024-09-05 02:54

import apps.custom_storage
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0022_rename_img_url_league_img_alter_brolympics_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_h2h',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_h2h',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_team',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_team',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brolympics',
            name='img',
            field=models.ImageField(null=True, storage=apps.custom_storage.FirebaseStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='league',
            name='img',
            field=models.ImageField(null=True, storage=apps.custom_storage.FirebaseStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(storage=apps.custom_storage.FirebaseStorage(), upload_to=''),
        ),
    ]
