# Generated by Django 4.2.2 on 2024-09-05 04:12

import apps.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0023_event_h2h_location_event_h2h_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(null=True, storage=apps.custom_storage.FirebaseStorage(), upload_to=''),
        ),
    ]
