steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  # Create migrations with prod settings
  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    entrypoint: "python"
    args:
      [
        "manage.py",
        "makemigrations",
        "--check",
        "--dry-run",
        "--settings=api.settings.prod",
      ]
    env:
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
    secretEnv:
      - django_secret_key
      - firebase_storage_bucket
      - db_name
      - db_user
      - db_password
      - db_host
      - firebase_service_account
      - api-cloudrun-service-url

  # Run database migrations
  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    entrypoint: "python"
    args: ["manage.py", "migrate", "--settings=api.settings.prod"]
    env:
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
    secretEnv:
      - django_secret_key
      - firebase_storage_bucket
      - db_name
      - db_user
      - db_password
      - db_host
      - firebase_service_account
      - api-cloudrun-service-url

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "--region"
      - "us-east5"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "--set-secrets"
      - "firebase_service_account=firebase_service_account:latest,django_secret_key=django_secret_key:latest,firebase_storage_bucket=firebase_storage_bucket:latest,db_name=db_name:latest,db_user=db_user:latest,db_password=db_password:latest,db_host=db_host:latest,api-cloudrun-service-url=api-cloudrun-service-url:latest"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/django_secret_key/versions/latest
      env: "django_secret_key"
    - versionName: projects/$PROJECT_ID/secrets/firebase_storage_bucket/versions/latest
      env: "firebase_storage_bucket"
    - versionName: projects/$PROJECT_ID/secrets/db_name/versions/latest
      env: "db_name"
    - versionName: projects/$PROJECT_ID/secrets/db_user/versions/latest
      env: "db_user"
    - versionName: projects/$PROJECT_ID/secrets/db_password/versions/latest
      env: "db_password"
    - versionName: projects/$PROJECT_ID/secrets/db_host/versions/latest
      env: "db_host"
    - versionName: projects/$PROJECT_ID/secrets/firebase_service_account/versions/latest
      env: "firebase_service_account"
    - versionName: projects/$PROJECT_ID/secrets/api-cloudrun-service-url/versions/latest
      env: "api-cloudrun-service-url"
