# Generated by Django 4.2.2 on 2024-09-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
