# Generated by Django 4.2.2 on 2024-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_firebaseuser_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='imgUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
