# Generated by Django 4.2.2 on 2024-09-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_imgurl_firebaseuser_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='img_url',
        ),
    ]
