# Generated by Django 4.2.2 on 2024-09-04 16:48

import apps.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_firebaseuser_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='img',
            field=models.ImageField(default='', storage=apps.custom_storage.FirebaseStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
