# Generated by Django 4.2.2 on 2024-09-05 04:12

import apps.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_firebaseuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='img',
            field=models.ImageField(null=True, storage=apps.custom_storage.FirebaseStorage(), upload_to=''),
        ),
    ]
